#!/bin/bash

# This is a launch script for the App update scheduler. 

if type -p java; then
    echo found java executable in PATH
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    osascript -e 'tell application "System Events" to display dialog "Java version 1.8+ is required" with icon file ":System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:AlertNoteIcon.icns"'
    osascript -e 'tell application "Safari" to open location "http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html"'
     _java="$JAVA_HOME/bin/java"
else
    osascript -e 'tell application "System Events" to display dialog "Java version 1.8+ is required" with icon file ":System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:AlertNoteIcon.icns"'
    osascript -e 'tell application "Safari" to open location "http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html"'
fi

if [[ "$_java" ]]; then
    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    echo version "$version"
    if [[ "$version" > "1.8" ]]; then
        java -jar /Applications/App-Update-Scheduler.app/App-Update-Scheduler.jar
    else         
        osascript -e 'tell application "System Events" to display dialog "Java version 1.8+ is required" with icon file ":System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:AlertNoteIcon.icns"'
        osascript -e 'tell application "Safari" to open location "http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html"'
    fi
fi

